### ISSUE TITLE
License ambiguity again

### ISSUE THREAD

**Issue by pghmcfc** [briandfoy/test-output#5]
This old chestnut again.

The 'LICENSE' file says that the module is licensed "under the same terms as perl itself, under the Artistic License 2.0", which is self-contradicting because perl is licensed under either GPL or Artistic 1 licenses, not Artistic 2. The text in the module file itself says "same as perl", without mentioning Artistic 2.0. I suspect you mean to license the module as Artistic 2.0, in which case it would be better to get rid of the "same as perl" text everywhere and just say "Artistic 2.0" instead.

**Comment by briandfoy** [comment]
You are correct (so if you find it again you don't have to type so much :). It's patched in the repo and will be part of the next release.

**Comment by pghmcfc** [comment]
Didn't need to type much actually - mainly copy and paste from the last one :)
