### ISSUE TITLE
syntax errors in pod code examples

### ISSUE THREAD

**Issue by hexcoder-** [briandfoy/test-output#6]
Hi, in the code examples for section TESTS subsection OUTPUT, subsubsection output_is, output_isnt, there are two code blocks (following 

> is functionally equivalent to
.

One for `output_is`

```
 stdout_is(sub {print "foo";},'foo')
    && stderr_is(sub {print STDERR "bar";'bar');
```
which should be
```
 stdout_is(sub {print "foo";},'foo')
    && stderr_is(sub {print STDERR "bar";},'bar');
```
(adds the missing curly closing brace and comma before the last argument of `stderr_is`)

and another one for `output_isnt`
```
  stdout_is(sub {print "foo";},'bar')
    && stderr_is(sub {print STDERR "bar";'foo');
```
which should be
```
  stdout_isnt(sub {print "foo";},'bar')
    && stderr_isnt(sub {print STDERR "bar";},'foo');
```
(changes std*_is -> std*_isnt and adds the missing curly brace and comma)

**Comment by briandfoy** [comment]
This should be fixed in ddbc014f54ccf68657a5bbdf9719a5734ec7c41d. Thanks,
