### ISSUE TITLE
Double encoding in Changes

### ISSUE THREAD

**Issue by benkasminbullock** [briandfoy/test-output#9]
https://fastapi.metacpan.org/source/BDFOY/Test-Output-1.033/Changes

The problem is here:

This was noticed by Tina MÃ¼ller in https://github.com/os-autoinst/os-autoinst/pull/1622

While I am aware that I'm teaching my grandmother to suck eggs, it's most likely that you read in a file as bytes (no :encoding(utf8)) then wrote it out again as `:encoding(utf8)` so that byte data was upgraded into characters accidentally.

**Comment by briandfoy** [comment]
This will be part of the next release. Thanks,
